# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\Analyze.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_analyze_data(object):
    def setupUi(self, analyze_data):
        analyze_data.setObjectName("analyze_data")
        analyze_data.resize(1024, 540)
        self.background = QtWidgets.QLabel(analyze_data)
        self.background.setGeometry(QtCore.QRect(0, 0, 1024, 600))
        self.background.setText("")
        self.background.setObjectName("background")
        self.pushButton_back = QtWidgets.QPushButton(analyze_data)
        self.pushButton_back.setGeometry(QtCore.QRect(20, 20, 220, 80))
        font = QtGui.QFont()
        font.setFamily("Cooper Black")
        font.setPointSize(24)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_back.setFont(font)
        self.pushButton_back.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton_back.setIconSize(QtCore.QSize(16, 16))
        self.pushButton_back.setAutoDefault(False)
        self.pushButton_back.setObjectName("pushButton_back")
        self.label_title = QtWidgets.QLabel(analyze_data)
        self.label_title.setGeometry(QtCore.QRect(287, 20, 450, 80))
        font = QtGui.QFont()
        font.setFamily("Cooper Black")
        font.setPointSize(34)
        font.setBold(False)
        font.setWeight(50)
        self.label_title.setFont(font)
        self.label_title.setLineWidth(-3)
        self.label_title.setAlignment(QtCore.Qt.AlignCenter)
        self.label_title.setWordWrap(True)
        self.label_title.setObjectName("label_title")
        self.label_image = QtWidgets.QLabel(analyze_data)
        self.label_image.setGeometry(QtCore.QRect(638, 120, 320, 320))
        font = QtGui.QFont()
        font.setFamily("Cooper Black")
        font.setPointSize(36)
        font.setBold(False)
        font.setWeight(50)
        self.label_image.setFont(font)
        self.label_image.setLineWidth(-3)
        self.label_image.setAlignment(QtCore.Qt.AlignCenter)
        self.label_image.setWordWrap(True)
        self.label_image.setObjectName("label_image")
        self.label_explanation_side = QtWidgets.QLabel(analyze_data)
        self.label_explanation_side.setGeometry(QtCore.QRect(50, 120, 500, 320))
        font = QtGui.QFont()
        font.setFamily("Cooper Black")
        font.setPointSize(22)
        font.setBold(False)
        font.setWeight(50)
        self.label_explanation_side.setFont(font)
        self.label_explanation_side.setLineWidth(-3)
        self.label_explanation_side.setAlignment(QtCore.Qt.AlignCenter)
        self.label_explanation_side.setWordWrap(True)
        self.label_explanation_side.setObjectName("label_explanation_side")
        self.pushButton_next = QtWidgets.QPushButton(analyze_data)
        self.pushButton_next.setGeometry(QtCore.QRect(620, 455, 340, 60))
        font = QtGui.QFont()
        font.setFamily("Cooper Black")
        font.setPointSize(26)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_next.setFont(font)
        self.pushButton_next.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton_next.setIconSize(QtCore.QSize(16, 16))
        self.pushButton_next.setAutoDefault(False)
        self.pushButton_next.setObjectName("pushButton_next")
        self.pushButton_previous = QtWidgets.QPushButton(analyze_data)
        self.pushButton_previous.setGeometry(QtCore.QRect(50, 455, 340, 60))
        font = QtGui.QFont()
        font.setFamily("Cooper Black")
        font.setPointSize(26)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_previous.setFont(font)
        self.pushButton_previous.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton_previous.setIconSize(QtCore.QSize(16, 16))
        self.pushButton_previous.setAutoDefault(False)
        self.pushButton_previous.setObjectName("pushButton_previous")

        self.retranslateUi(analyze_data)
        QtCore.QMetaObject.connectSlotsByName(analyze_data)

    def retranslateUi(self, analyze_data):
        _translate = QtCore.QCoreApplication.translate
        analyze_data.setWindowTitle(_translate("analyze_data", "Form"))
        self.pushButton_back.setText(_translate("analyze_data", "BACK"))
        self.label_title.setText(_translate("analyze_data", "TITLE"))
        self.label_image.setText(_translate("analyze_data", "IMAGE"))
        self.label_explanation_side.setText(_translate("analyze_data", "SIDE"))
        self.pushButton_next.setText(_translate("analyze_data", "NEXT "))
        self.pushButton_previous.setText(_translate("analyze_data", "Previous"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    analyze_data = QtWidgets.QWidget()
    ui = Ui_analyze_data()
    ui.setupUi(analyze_data)
    analyze_data.show()
    sys.exit(app.exec_())
