# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\Classroom.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Classroom(object):
    def setupUi(self, Classroom):
        Classroom.setObjectName("Classroom")
        Classroom.resize(1024, 538)
        self.pushButton_back = QtWidgets.QPushButton(Classroom)
        self.pushButton_back.setGeometry(QtCore.QRect(10, 10, 281, 71))
        font = QtGui.QFont()
        font.setFamily("Cooper Black")
        font.setPointSize(24)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_back.setFont(font)
        self.pushButton_back.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton_back.setIconSize(QtCore.QSize(16, 16))
        self.pushButton_back.setAutoDefault(False)
        self.pushButton_back.setObjectName("pushButton_back")
        self.pushButton_previous = QtWidgets.QPushButton(Classroom)
        self.pushButton_previous.setGeometry(QtCore.QRect(70, 460, 281, 71))
        font = QtGui.QFont()
        font.setFamily("Cooper Black")
        font.setPointSize(24)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_previous.setFont(font)
        self.pushButton_previous.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton_previous.setIconSize(QtCore.QSize(16, 16))
        self.pushButton_previous.setAutoDefault(False)
        self.pushButton_previous.setObjectName("pushButton_previous")
        self.pushButton_next = QtWidgets.QPushButton(Classroom)
        self.pushButton_next.setGeometry(QtCore.QRect(660, 460, 281, 71))
        font = QtGui.QFont()
        font.setFamily("Cooper Black")
        font.setPointSize(24)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_next.setFont(font)
        self.pushButton_next.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton_next.setIconSize(QtCore.QSize(16, 16))
        self.pushButton_next.setAutoDefault(False)
        self.pushButton_next.setObjectName("pushButton_next")
        self.label_chalkboard = QtWidgets.QLabel(Classroom)
        self.label_chalkboard.setGeometry(QtCore.QRect(390, 130, 461, 201))
        font = QtGui.QFont()
        font.setFamily("Cooper Black")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.label_chalkboard.setFont(font)
        self.label_chalkboard.setLineWidth(-3)
        self.label_chalkboard.setScaledContents(False)
        self.label_chalkboard.setAlignment(QtCore.Qt.AlignCenter)
        self.label_chalkboard.setWordWrap(True)
        self.label_chalkboard.setObjectName("label_chalkboard")
        self.background = QtWidgets.QLabel(Classroom)
        self.background.setGeometry(QtCore.QRect(0, 0, 1024, 600))
        self.background.setText("")
        self.background.setPixmap(QtGui.QPixmap(".\\../src/images/background/Classroom.png"))
        self.background.setScaledContents(True)
        self.background.setObjectName("background")
        self.label_chalkboard_title = QtWidgets.QLabel(Classroom)
        self.label_chalkboard_title.setGeometry(QtCore.QRect(390, 80, 451, 51))
        font = QtGui.QFont()
        font.setFamily("Cooper Black")
        font.setPointSize(28)
        font.setBold(False)
        font.setWeight(50)
        self.label_chalkboard_title.setFont(font)
        self.label_chalkboard_title.setLineWidth(-3)
        self.label_chalkboard_title.setAlignment(QtCore.Qt.AlignCenter)
        self.label_chalkboard_title.setWordWrap(True)
        self.label_chalkboard_title.setObjectName("label_chalkboard_title")
        self.archie = QtWidgets.QLabel(Classroom)
        self.archie.setGeometry(QtCore.QRect(50, 110, 350, 350))
        self.archie.setText("")
        self.archie.setObjectName("archie")
        self.background.raise_()
        self.pushButton_back.raise_()
        self.pushButton_previous.raise_()
        self.pushButton_next.raise_()
        self.label_chalkboard_title.raise_()
        self.archie.raise_()
        self.label_chalkboard.raise_()

        self.retranslateUi(Classroom)
        QtCore.QMetaObject.connectSlotsByName(Classroom)

    def retranslateUi(self, Classroom):
        _translate = QtCore.QCoreApplication.translate
        Classroom.setWindowTitle(_translate("Classroom", "Form"))
        self.pushButton_back.setText(_translate("Classroom", "BACK"))
        self.pushButton_previous.setText(_translate("Classroom", "Previous"))
        self.pushButton_next.setText(_translate("Classroom", "Next"))
        self.label_chalkboard.setText(_translate("Classroom", "What are we going to learn about??"))
        self.label_chalkboard_title.setText(_translate("Classroom", "TOPIC"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Classroom = QtWidgets.QWidget()
    ui = Ui_Classroom()
    ui.setupUi(Classroom)
    Classroom.show()
    sys.exit(app.exec_())
