# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\home.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Home_ui(object):
    def setupUi(self, Home_ui):
        Home_ui.setObjectName("Home_ui")
        Home_ui.resize(1024, 538)
        self.splitter = QtWidgets.QSplitter(Home_ui)
        self.splitter.setGeometry(QtCore.QRect(460, 150, 541, 351))
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName("splitter")
        self.pushButton_H_Simulation = QtWidgets.QPushButton(self.splitter)
        font = QtGui.QFont()
        font.setFamily("Cooper Black")
        font.setPointSize(28)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_H_Simulation.setFont(font)
        self.pushButton_H_Simulation.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton_H_Simulation.setIconSize(QtCore.QSize(16, 16))
        self.pushButton_H_Simulation.setAutoDefault(False)
        self.pushButton_H_Simulation.setObjectName("pushButton_H_Simulation")
        self.pushButton_H_LiveData = QtWidgets.QPushButton(self.splitter)
        font = QtGui.QFont()
        font.setFamily("Cooper Black")
        font.setPointSize(28)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_H_LiveData.setFont(font)
        self.pushButton_H_LiveData.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton_H_LiveData.setIconSize(QtCore.QSize(16, 16))
        self.pushButton_H_LiveData.setAutoDefault(False)
        self.pushButton_H_LiveData.setObjectName("pushButton_H_LiveData")
        self.pushButton_H_Learn = QtWidgets.QPushButton(self.splitter)
        font = QtGui.QFont()
        font.setFamily("Cooper Black")
        font.setPointSize(28)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_H_Learn.setFont(font)
        self.pushButton_H_Learn.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton_H_Learn.setIconSize(QtCore.QSize(16, 16))
        self.pushButton_H_Learn.setAutoDefault(False)
        self.pushButton_H_Learn.setObjectName("pushButton_H_Learn")
        self.pushButton_H_Quiz = QtWidgets.QPushButton(self.splitter)
        font = QtGui.QFont()
        font.setFamily("Cooper Black")
        font.setPointSize(28)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_H_Quiz.setFont(font)
        self.pushButton_H_Quiz.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton_H_Quiz.setIconSize(QtCore.QSize(16, 16))
        self.pushButton_H_Quiz.setAutoDefault(False)
        self.pushButton_H_Quiz.setObjectName("pushButton_H_Quiz")
        self.label_H_main = QtWidgets.QLabel(Home_ui)
        self.label_H_main.setGeometry(QtCore.QRect(150, 30, 640, 69))
        font = QtGui.QFont()
        font.setFamily("Cooper Black")
        font.setPointSize(36)
        font.setBold(False)
        font.setWeight(50)
        self.label_H_main.setFont(font)
        self.label_H_main.setAlignment(QtCore.Qt.AlignCenter)
        self.label_H_main.setObjectName("label_H_main")
        self.background = QtWidgets.QLabel(Home_ui)
        self.background.setGeometry(QtCore.QRect(0, 0, 1024, 600))
        self.background.setText("")
        self.background.setScaledContents(False)
        self.background.setObjectName("background")
        self.archie = QtWidgets.QLabel(Home_ui)
        self.archie.setGeometry(QtCore.QRect(30, 130, 400, 400))
        self.archie.setText("")
        self.archie.setScaledContents(False)
        self.archie.setObjectName("archie")
        self.background.raise_()
        self.splitter.raise_()
        self.label_H_main.raise_()
        self.archie.raise_()

        self.retranslateUi(Home_ui)
        QtCore.QMetaObject.connectSlotsByName(Home_ui)

    def retranslateUi(self, Home_ui):
        _translate = QtCore.QCoreApplication.translate
        Home_ui.setWindowTitle(_translate("Home_ui", "Form"))
        self.pushButton_H_Simulation.setText(_translate("Home_ui", "Simulation"))
        self.pushButton_H_LiveData.setText(_translate("Home_ui", "Live Data"))
        self.pushButton_H_Learn.setText(_translate("Home_ui", "Learning Module"))
        self.pushButton_H_Quiz.setText(_translate("Home_ui", "Quiz"))
        self.label_H_main.setText(_translate("Home_ui", "Archie\'s AquaQuest"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Home_ui = QtWidgets.QWidget()
    ui = Ui_Home_ui()
    ui.setupUi(Home_ui)
    Home_ui.show()
    sys.exit(app.exec_())
