# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\home.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class UI_Home(object):
    def setupUi(self, Home_ui):
        Home_ui.setObjectName("Home_ui")
        Home_ui.resize(940, 700)
        self.splitter = QtWidgets.QSplitter(Home_ui)
        self.splitter.setGeometry(QtCore.QRect(50, 160, 841, 501))
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName("splitter")
        self.pushButton_H_Simulation = QtWidgets.QPushButton(self.splitter)
        font = QtGui.QFont()
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_H_Simulation.setFont(font)
        self.pushButton_H_Simulation.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton_H_Simulation.setIconSize(QtCore.QSize(16, 16))
        self.pushButton_H_Simulation.setAutoDefault(False)
        self.pushButton_H_Simulation.setObjectName("pushButton_H_Simulation")
        self.pushButton_H_LiveData = QtWidgets.QPushButton(self.splitter)
        font = QtGui.QFont()
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_H_LiveData.setFont(font)
        self.pushButton_H_LiveData.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton_H_LiveData.setIconSize(QtCore.QSize(16, 16))
        self.pushButton_H_LiveData.setAutoDefault(False)
        self.pushButton_H_LiveData.setObjectName("pushButton_H_LiveData")
        self.pushButton_H_Learn = QtWidgets.QPushButton(self.splitter)
        font = QtGui.QFont()
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_H_Learn.setFont(font)
        self.pushButton_H_Learn.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton_H_Learn.setIconSize(QtCore.QSize(16, 16))
        self.pushButton_H_Learn.setAutoDefault(False)
        self.pushButton_H_Learn.setObjectName("pushButton_H_Learn")
        self.pushButton_H_Quiz = QtWidgets.QPushButton(self.splitter)
        font = QtGui.QFont()
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_H_Quiz.setFont(font)
        self.pushButton_H_Quiz.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton_H_Quiz.setIconSize(QtCore.QSize(16, 16))
        self.pushButton_H_Quiz.setAutoDefault(False)
        self.pushButton_H_Quiz.setObjectName("pushButton_H_Quiz")
        self.label_H_main = QtWidgets.QLabel(Home_ui)
        self.label_H_main.setGeometry(QtCore.QRect(310, 50, 325, 64))
        font = QtGui.QFont()
        font.setPointSize(32)
        font.setBold(True)
        font.setWeight(75)
        self.label_H_main.setFont(font)
        self.label_H_main.setObjectName("label_H_main")

        self.retranslateUi(Home_ui)
        QtCore.QMetaObject.connectSlotsByName(Home_ui)

    def retranslateUi(self, Home_ui):
        _translate = QtCore.QCoreApplication.translate
        Home_ui.setWindowTitle(_translate("Home_ui", "Form"))
        self.pushButton_H_Simulation.setText(_translate("Home_ui", "Simulation"))
        self.pushButton_H_LiveData.setText(_translate("Home_ui", "Live Data"))
        self.pushButton_H_Learn.setText(_translate("Home_ui", "Learning Module"))
        self.pushButton_H_Quiz.setText(_translate("Home_ui", "Quiz"))
        self.label_H_main.setText(_translate("Home_ui", "ECO-DRONE"))


