# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\intro.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1024, 540)
        self.background = QtWidgets.QLabel(Form)
        self.background.setGeometry(QtCore.QRect(0, 0, 1024, 540))
        self.background.setText("")
        self.background.setScaledContents(True)
        self.background.setObjectName("background")
        self.archie = QtWidgets.QLabel(Form)
        self.archie.setGeometry(QtCore.QRect(30, 90, 320, 320))
        font = QtGui.QFont()
        font.setFamily("Cooper Black")
        font.setPointSize(32)
        font.setBold(False)
        font.setWeight(50)
        self.archie.setFont(font)
        self.archie.setLineWidth(-3)
        self.archie.setAlignment(QtCore.Qt.AlignCenter)
        self.archie.setWordWrap(True)
        self.archie.setObjectName("archie")
        self.label_explanation = QtWidgets.QLabel(Form)
        self.label_explanation.setGeometry(QtCore.QRect(380, 30, 601, 401))
        font = QtGui.QFont()
        font.setFamily("Cooper Black")
        font.setPointSize(18)
        font.setBold(False)
        font.setWeight(50)
        self.label_explanation.setFont(font)
        self.label_explanation.setLineWidth(-3)
        self.label_explanation.setAlignment(QtCore.Qt.AlignCenter)
        self.label_explanation.setWordWrap(True)
        self.label_explanation.setObjectName("label_explanation")
        self.pushButton_bottom = QtWidgets.QPushButton(Form)
        self.pushButton_bottom.setGeometry(QtCore.QRect(250, 449, 501, 71))
        font = QtGui.QFont()
        font.setFamily("Cooper Black")
        font.setPointSize(26)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_bottom.setFont(font)
        self.pushButton_bottom.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton_bottom.setIconSize(QtCore.QSize(16, 16))
        self.pushButton_bottom.setAutoDefault(False)
        self.pushButton_bottom.setObjectName("pushButton_bottom")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.archie.setText(_translate("Form", "IMAGE"))
        self.label_explanation.setText(_translate("Form", "Hi there! I’m Archie! \n"
"\n"
"I’m an alligator snapping turtle, and I’ll be your guide today! I live right here in Indiana — in rivers, lakes, and ponds. \n"
"\n"
"Turtles like me are endangered. That’s why it’s so important to keep our water clean — for me, for you, and for all the amazing plants and animals that live here. \n"
"\n"
"We’re about to test some water!"))
        self.pushButton_bottom.setText(_translate("Form", "Let\'s Dive In!!"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
