# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\Learning.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class UI_learning(object):
    def setupUi(self, learning_ui):
        learning_ui.setObjectName("learning_ui")
        learning_ui.resize(940, 700)
        self.label_simulation = QtWidgets.QLabel(learning_ui)
        self.label_simulation.setGeometry(QtCore.QRect(230, 310, 486, 64))
        font = QtGui.QFont()
        font.setPointSize(32)
        font.setBold(True)
        font.setWeight(75)
        self.label_simulation.setFont(font)
        self.label_simulation.setObjectName("label_simulation")
        self.pushButton_back = QtWidgets.QPushButton(learning_ui)
        self.pushButton_back.setGeometry(QtCore.QRect(20, 10, 301, 101))
        font = QtGui.QFont()
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_back.setFont(font)
        self.pushButton_back.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton_back.setIconSize(QtCore.QSize(16, 16))
        self.pushButton_back.setAutoDefault(False)
        self.pushButton_back.setObjectName("pushButton_back")

        self.retranslateUi(learning_ui)
        QtCore.QMetaObject.connectSlotsByName(learning_ui)

    def retranslateUi(self, learning_ui):
        _translate = QtCore.QCoreApplication.translate
        learning_ui.setWindowTitle(_translate("learning_ui", "Form"))
        self.label_simulation.setText(_translate("learning_ui", "Learning Modules "))
        self.pushButton_back.setText(_translate("learning_ui", "BACK"))

