# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\Learning.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class UI_learning(object):
    def setupUi(self, learning_ui):
        learning_ui.setObjectName("learning_ui")
        learning_ui.resize(940, 700)
        self.label_L_title = QtWidgets.QLabel(learning_ui)
        self.label_L_title.setGeometry(QtCore.QRect(360, 20, 500, 122))
        font = QtGui.QFont()
        font.setFamily("Cooper Black")
        font.setPointSize(32)
        font.setBold(False)
        font.setWeight(50)
        self.label_L_title.setFont(font)
        self.label_L_title.setLineWidth(-3)
        self.label_L_title.setAlignment(QtCore.Qt.AlignCenter)
        self.label_L_title.setWordWrap(True)
        self.label_L_title.setObjectName("label_L_title")
        self.pushButton_L_parameters = QtWidgets.QPushButton(learning_ui)
        self.pushButton_L_parameters.setGeometry(QtCore.QRect(50, 170, 511, 122))
        font = QtGui.QFont()
        font.setFamily("Cooper Black")
        font.setPointSize(28)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_L_parameters.setFont(font)
        self.pushButton_L_parameters.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton_L_parameters.setIconSize(QtCore.QSize(16, 16))
        self.pushButton_L_parameters.setAutoDefault(False)
        self.pushButton_L_parameters.setObjectName("pushButton_L_parameters")
        self.pushButton_L_whyTest = QtWidgets.QPushButton(learning_ui)
        self.pushButton_L_whyTest.setGeometry(QtCore.QRect(50, 350, 511, 122))
        font = QtGui.QFont()
        font.setFamily("Cooper Black")
        font.setPointSize(28)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_L_whyTest.setFont(font)
        self.pushButton_L_whyTest.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton_L_whyTest.setIconSize(QtCore.QSize(16, 16))
        self.pushButton_L_whyTest.setAutoDefault(False)
        self.pushButton_L_whyTest.setObjectName("pushButton_L_whyTest")
        self.pushButton_L_howMove = QtWidgets.QPushButton(learning_ui)
        self.pushButton_L_howMove.setGeometry(QtCore.QRect(50, 530, 511, 122))
        font = QtGui.QFont()
        font.setFamily("Cooper Black")
        font.setPointSize(28)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_L_howMove.setFont(font)
        self.pushButton_L_howMove.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton_L_howMove.setIconSize(QtCore.QSize(16, 16))
        self.pushButton_L_howMove.setAutoDefault(False)
        self.pushButton_L_howMove.setObjectName("pushButton_L_howMove")
        self.pushButton_back = QtWidgets.QPushButton(learning_ui)
        self.pushButton_back.setGeometry(QtCore.QRect(20, 20, 281, 71))
        font = QtGui.QFont()
        font.setFamily("Cooper Black")
        font.setPointSize(24)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_back.setFont(font)
        self.pushButton_back.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton_back.setIconSize(QtCore.QSize(16, 16))
        self.pushButton_back.setAutoDefault(False)
        self.pushButton_back.setObjectName("pushButton_back")
        self.background = QtWidgets.QLabel(learning_ui)
        self.background.setGeometry(QtCore.QRect(0, 0, 940, 700))
        self.background.setText("")
        self.background.setObjectName("background")
        self.background.raise_()
        self.label_L_title.raise_()
        self.pushButton_L_parameters.raise_()
        self.pushButton_L_whyTest.raise_()
        self.pushButton_L_howMove.raise_()
        self.pushButton_back.raise_()

        self.retranslateUi(learning_ui)
        QtCore.QMetaObject.connectSlotsByName(learning_ui)

    def retranslateUi(self, learning_ui):
        _translate = QtCore.QCoreApplication.translate
        learning_ui.setWindowTitle(_translate("learning_ui", "Form"))
        self.label_L_title.setText(_translate("learning_ui", "What are we going to learn about??"))
        self.pushButton_L_parameters.setText(_translate("learning_ui", "how to test water?"))
        self.pushButton_L_whyTest.setText(_translate("learning_ui", "Why test water"))
        self.pushButton_L_howMove.setText(_translate("learning_ui", "How Water Moves "))
        self.pushButton_back.setText(_translate("learning_ui", "BACK"))
