# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\LiveData.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class UI_live_data(object):
    def setupUi(self, live_data_ui):
        live_data_ui.setObjectName("live_data_ui")
        live_data_ui.resize(940, 700)
        self.pushButton_back = QtWidgets.QPushButton(live_data_ui)
        self.pushButton_back.setGeometry(QtCore.QRect(20, 20, 301, 101))
        font = QtGui.QFont()
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_back.setFont(font)
        self.pushButton_back.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton_back.setIconSize(QtCore.QSize(16, 16))
        self.pushButton_back.setAutoDefault(False)
        self.pushButton_back.setObjectName("pushButton_back")
        self.label_LiveData = QtWidgets.QLabel(live_data_ui)
        self.label_LiveData.setGeometry(QtCore.QRect(300, 310, 288, 64))
        font = QtGui.QFont()
        font.setPointSize(32)
        font.setBold(True)
        font.setWeight(75)
        self.label_LiveData.setFont(font)
        self.label_LiveData.setObjectName("label_LiveData")

        self.retranslateUi(live_data_ui)
        QtCore.QMetaObject.connectSlotsByName(live_data_ui)

    def retranslateUi(self, live_data_ui):
        _translate = QtCore.QCoreApplication.translate
        live_data_ui.setWindowTitle(_translate("live_data_ui", "Form"))
        self.pushButton_back.setText(_translate("live_data_ui", "BACK"))
        self.label_LiveData.setText(_translate("live_data_ui", "Live Data "))

