# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\Quiz.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class UI_quiz(object):
    def setupUi(self, quiz_ui):
        quiz_ui.setObjectName("quiz_ui")
        quiz_ui.resize(940, 700)
        self.pushButton_back = QtWidgets.QPushButton(quiz_ui)
        self.pushButton_back.setGeometry(QtCore.QRect(20, 10, 301, 101))
        font = QtGui.QFont()
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_back.setFont(font)
        self.pushButton_back.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton_back.setIconSize(QtCore.QSize(16, 16))
        self.pushButton_back.setAutoDefault(False)
        self.pushButton_back.setObjectName("pushButton_back")
        self.label_learning = QtWidgets.QLabel(quiz_ui)
        self.label_learning.setGeometry(QtCore.QRect(380, 310, 119, 64))
        font = QtGui.QFont()
        font.setPointSize(32)
        font.setBold(True)
        font.setWeight(75)
        self.label_learning.setFont(font)
        self.label_learning.setObjectName("label_learning")

        self.retranslateUi(quiz_ui)
        QtCore.QMetaObject.connectSlotsByName(quiz_ui)

    def retranslateUi(self, quiz_ui):
        _translate = QtCore.QCoreApplication.translate
        quiz_ui.setWindowTitle(_translate("quiz_ui", "Form"))
        self.pushButton_back.setText(_translate("quiz_ui", "BACK"))
        self.label_learning.setText(_translate("quiz_ui", "Quiz"))


