# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\Quiz.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class UI_quiz(object):
    def setupUi(self, quiz_ui):
        quiz_ui.setObjectName("quiz_ui")
        quiz_ui.resize(940, 700)
        self.pushButton_back = QtWidgets.QPushButton(quiz_ui)
        self.pushButton_back.setGeometry(QtCore.QRect(20, 20, 281, 71))
        font = QtGui.QFont()
        font.setFamily("Cooper Black")
        font.setPointSize(24)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_back.setFont(font)
        self.pushButton_back.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton_back.setIconSize(QtCore.QSize(16, 16))
        self.pushButton_back.setAutoDefault(False)
        self.pushButton_back.setObjectName("pushButton_back")
        self.pushButton_Q_answer1 = QtWidgets.QPushButton(quiz_ui)
        self.pushButton_Q_answer1.setGeometry(QtCore.QRect(40, 320, 450, 100))
        font = QtGui.QFont()
        font.setFamily("Cooper Black")
        font.setPointSize(16)
        self.pushButton_Q_answer1.setFont(font)
        self.pushButton_Q_answer1.setObjectName("pushButton_Q_answer1")
        self.label_Q_question = QtWidgets.QLabel(quiz_ui)
        self.label_Q_question.setGeometry(QtCore.QRect(40, 140, 450, 141))
        font = QtGui.QFont()
        font.setFamily("Cooper Black")
        font.setPointSize(18)
        self.label_Q_question.setFont(font)
        self.label_Q_question.setAlignment(QtCore.Qt.AlignCenter)
        self.label_Q_question.setWordWrap(True)
        self.label_Q_question.setObjectName("label_Q_question")
        self.pushButton_Q_answer2 = QtWidgets.QPushButton(quiz_ui)
        self.pushButton_Q_answer2.setGeometry(QtCore.QRect(40, 440, 450, 100))
        font = QtGui.QFont()
        font.setFamily("Cooper Black")
        font.setPointSize(16)
        self.pushButton_Q_answer2.setFont(font)
        self.pushButton_Q_answer2.setObjectName("pushButton_Q_answer2")
        self.pushButton_Q_answer3 = QtWidgets.QPushButton(quiz_ui)
        self.pushButton_Q_answer3.setGeometry(QtCore.QRect(40, 560, 450, 100))
        font = QtGui.QFont()
        font.setFamily("Cooper Black")
        font.setPointSize(16)
        self.pushButton_Q_answer3.setFont(font)
        self.pushButton_Q_answer3.setObjectName("pushButton_Q_answer3")
        self.background = QtWidgets.QLabel(quiz_ui)
        self.background.setGeometry(QtCore.QRect(0, 0, 940, 700))
        self.background.setText("")
        self.background.setObjectName("background")
        self.pushButton_Q_next = QtWidgets.QPushButton(quiz_ui)
        self.pushButton_Q_next.setGeometry(QtCore.QRect(540, 560, 331, 100))
        font = QtGui.QFont()
        font.setFamily("Cooper Black")
        font.setPointSize(16)
        self.pushButton_Q_next.setFont(font)
        self.pushButton_Q_next.setObjectName("pushButton_Q_next")
        self.label_Q_results = QtWidgets.QLabel(quiz_ui)
        self.label_Q_results.setGeometry(QtCore.QRect(520, 30, 381, 191))
        font = QtGui.QFont()
        font.setFamily("Cooper Black")
        font.setPointSize(18)
        self.label_Q_results.setFont(font)
        self.label_Q_results.setText("")
        self.label_Q_results.setAlignment(QtCore.Qt.AlignCenter)
        self.label_Q_results.setWordWrap(True)
        self.label_Q_results.setObjectName("label_Q_results")
        self.background.raise_()
        self.pushButton_back.raise_()
        self.pushButton_Q_answer1.raise_()
        self.label_Q_question.raise_()
        self.pushButton_Q_answer2.raise_()
        self.pushButton_Q_answer3.raise_()
        self.pushButton_Q_next.raise_()
        self.label_Q_results.raise_()

        self.retranslateUi(quiz_ui)
        QtCore.QMetaObject.connectSlotsByName(quiz_ui)

    def retranslateUi(self, quiz_ui):
        _translate = QtCore.QCoreApplication.translate
        quiz_ui.setWindowTitle(_translate("quiz_ui", "Form"))
        self.pushButton_back.setText(_translate("quiz_ui", "BACK"))
        self.pushButton_Q_answer1.setText(_translate("quiz_ui", "PushButton"))
        self.label_Q_question.setText(_translate("quiz_ui", "TextLabel"))
        self.pushButton_Q_answer2.setText(_translate("quiz_ui", "PushButton"))
        self.pushButton_Q_answer3.setText(_translate("quiz_ui", "PushButton"))
        self.pushButton_Q_next.setText(_translate("quiz_ui", "Next Question"))



