# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\Quiz.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_quiz_ui(object):
    def setupUi(self, quiz_ui):
        quiz_ui.setObjectName("quiz_ui")
        quiz_ui.resize(1039, 538)
        self.pushButton_back = QtWidgets.QPushButton(quiz_ui)
        self.pushButton_back.setGeometry(QtCore.QRect(20, 20, 281, 71))
        font = QtGui.QFont()
        font.setFamily("Cooper Black")
        font.setPointSize(24)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_back.setFont(font)
        self.pushButton_back.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton_back.setIconSize(QtCore.QSize(16, 16))
        self.pushButton_back.setAutoDefault(False)
        self.pushButton_back.setObjectName("pushButton_back")
        self.pushButton_Q_answer1 = QtWidgets.QPushButton(quiz_ui)
        self.pushButton_Q_answer1.setGeometry(QtCore.QRect(470, 170, 491, 75))
        font = QtGui.QFont()
        font.setFamily("Cooper Black")
        font.setPointSize(16)
        self.pushButton_Q_answer1.setFont(font)
        self.pushButton_Q_answer1.setObjectName("pushButton_Q_answer1")
        self.label_Q_question = QtWidgets.QLabel(quiz_ui)
        self.label_Q_question.setGeometry(QtCore.QRect(460, 20, 501, 121))
        font = QtGui.QFont()
        font.setFamily("Cooper Black")
        font.setPointSize(16)
        self.label_Q_question.setFont(font)
        self.label_Q_question.setAlignment(QtCore.Qt.AlignCenter)
        self.label_Q_question.setWordWrap(True)
        self.label_Q_question.setObjectName("label_Q_question")
        self.pushButton_Q_answer2 = QtWidgets.QPushButton(quiz_ui)
        self.pushButton_Q_answer2.setGeometry(QtCore.QRect(470, 260, 491, 75))
        font = QtGui.QFont()
        font.setFamily("Cooper Black")
        font.setPointSize(16)
        self.pushButton_Q_answer2.setFont(font)
        self.pushButton_Q_answer2.setObjectName("pushButton_Q_answer2")
        self.pushButton_Q_answer3 = QtWidgets.QPushButton(quiz_ui)
        self.pushButton_Q_answer3.setGeometry(QtCore.QRect(470, 350, 491, 75))
        font = QtGui.QFont()
        font.setFamily("Cooper Black")
        font.setPointSize(16)
        self.pushButton_Q_answer3.setFont(font)
        self.pushButton_Q_answer3.setObjectName("pushButton_Q_answer3")
        self.background = QtWidgets.QLabel(quiz_ui)
        self.background.setGeometry(QtCore.QRect(0, 0, 1024, 600))
        self.background.setText("")
        self.background.setObjectName("background")
        self.pushButton_Q_next = QtWidgets.QPushButton(quiz_ui)
        self.pushButton_Q_next.setGeometry(QtCore.QRect(470, 440, 491, 75))
        font = QtGui.QFont()
        font.setFamily("Cooper Black")
        font.setPointSize(16)
        self.pushButton_Q_next.setFont(font)
        self.pushButton_Q_next.setObjectName("pushButton_Q_next")
        self.label_Q_results = QtWidgets.QLabel(quiz_ui)
        self.label_Q_results.setGeometry(QtCore.QRect(30, 100, 411, 101))
        font = QtGui.QFont()
        font.setFamily("Cooper Black")
        font.setPointSize(16)
        self.label_Q_results.setFont(font)
        self.label_Q_results.setText("")
        self.label_Q_results.setAlignment(QtCore.Qt.AlignCenter)
        self.label_Q_results.setWordWrap(True)
        self.label_Q_results.setObjectName("label_Q_results")
        self.archie = QtWidgets.QLabel(quiz_ui)
        self.archie.setGeometry(QtCore.QRect(40, 190, 350, 350))
        self.archie.setText("")
        self.archie.setScaledContents(False)
        self.archie.setObjectName("archie")
        self.background.raise_()
        self.pushButton_back.raise_()
        self.pushButton_Q_answer1.raise_()
        self.label_Q_question.raise_()
        self.pushButton_Q_answer2.raise_()
        self.pushButton_Q_answer3.raise_()
        self.pushButton_Q_next.raise_()
        self.label_Q_results.raise_()
        self.archie.raise_()

        self.retranslateUi(quiz_ui)
        QtCore.QMetaObject.connectSlotsByName(quiz_ui)

    def retranslateUi(self, quiz_ui):
        _translate = QtCore.QCoreApplication.translate
        quiz_ui.setWindowTitle(_translate("quiz_ui", "Form"))
        self.pushButton_back.setText(_translate("quiz_ui", "BACK"))
        self.pushButton_Q_answer1.setText(_translate("quiz_ui", "PushButton"))
        self.label_Q_question.setText(_translate("quiz_ui", "TextLabel"))
        self.pushButton_Q_answer2.setText(_translate("quiz_ui", "PushButton"))
        self.pushButton_Q_answer3.setText(_translate("quiz_ui", "PushButton"))
        self.pushButton_Q_next.setText(_translate("quiz_ui", "Next Question"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    quiz_ui = QtWidgets.QWidget()
    ui = Ui_quiz_ui()
    ui.setupUi(quiz_ui)
    quiz_ui.show()
    sys.exit(app.exec_())
