# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\simulation.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class UI_simulation(object):
    def setupUi(self, simulation_ui):
        simulation_ui.setObjectName("simulation_ui")
        simulation_ui.resize(940, 700)
        self.pushButton_back = QtWidgets.QPushButton(simulation_ui)
        self.pushButton_back.setGeometry(QtCore.QRect(20, 10, 301, 101))
        font = QtGui.QFont()
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_back.setFont(font)
        self.pushButton_back.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton_back.setIconSize(QtCore.QSize(16, 16))
        self.pushButton_back.setAutoDefault(False)
        self.pushButton_back.setObjectName("pushButton_back")
        self.label_simulation = QtWidgets.QLabel(simulation_ui)
        self.label_simulation.setGeometry(QtCore.QRect(350, 310, 288, 64))
        font = QtGui.QFont()
        font.setPointSize(32)
        font.setBold(True)
        font.setWeight(75)
        self.label_simulation.setFont(font)
        self.label_simulation.setObjectName("label_simulation")

        self.retranslateUi(simulation_ui)
        QtCore.QMetaObject.connectSlotsByName(simulation_ui)

    def retranslateUi(self, simulation_ui):
        _translate = QtCore.QCoreApplication.translate
        simulation_ui.setWindowTitle(_translate("simulation_ui", "Form"))
        self.pushButton_back.setText(_translate("simulation_ui", "BACK"))
        self.label_simulation.setText(_translate("simulation_ui", "Simulation"))


